### ISSUE TITLE
l1norm_d  report errors

### ISSUE THREAD

**Issue by caoyuanbao** [HuiChen24/IMRAM#2]
I have an error here
![image](https://user-images.githubusercontent.com/18445923/89121630-0852b180-d4f3-11ea-8e53-ba019619a312.png)
And I have a question, where is its implement

**Comment by HuiChen24** [comment]
I believe that the default setting of raw_features_norm is not "l1norm" or "clipped_l1norm", and thus l1norm_d will not be activated here. Actually, our code is based on [SCAN.](https://github.com/kuanghuei/SCAN) You can turn to them for help with this function.
