### ISSUE TITLE
How much GPU Memory is required to run IMRAM (step=2, 3)?

### ISSUE THREAD

**Issue by liuyyy111** [HuiChen24/IMRAM#5]
Hi Hui, thanks for your open-sourcing and appreciate your efforts on it!

I failed to run the code on colab with 16G GPU Memory, so I want to know that how much GPU Memory I have at least to run it

**Comment by jacobswan1** [comment]
So I'm using a 4-GPU node with 16 GB memory per GPU, I can run the step=3 mode while can only hold half of the BATCHSIZE than the provided setting, which has some negative effect for the final performances. I think to change the code into PyTorch Data Distributed and AMP mode (PyTorch >=1.6) will largely reduce the GPU memory demand. I was planning to help to do this but got too much stuff recently.
